name: Go Test

on:
  push:

jobs:
  test:
    name: "test go services"
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: true
      - name: Test
        run: go test ./grpczerrors ./...